spring:
  application:
    name: ED_API
  
  config: 
     import:  optional:configserver:http://localhost:8888
 
server:
  port: 4044
  
  
  
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  paths-to-match: /Eligibility/**

  
