spring:
  application:
    name: CO_API
  datasource: 
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/jrtp701db
   
   username: root
   password: root
 
  mail:
    host: smtp.gmail.com
    port: 587
    username: sambhajiasalkar850@gmail.com
    password: rphy zzqp xrmx ynwb
    properties:
      mail:
       transport:
          protocol: smtp
       smtp:
        auth: true
        starttls:
         enable: true
  jpa: 
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
server:
 port: 4044
 
mailbody:
 registeruser:
    location: src/main/java/com/nt/service/user_registration.txt
 recoverpass:
    location: src/main/java/com/nt/service/recover_password.txt