spring:
  application:
    name: CO_API
  mail:
    host: smtp.gmail.com
    port: 587
    username: sambhajiasalkar850@gmail.com
    password: pvhf qxwz bnme jahg
    properties:
      mail:
       transport:
          protocol: smtp
       smtp:
        auth: true
        starttls:
         enable: true
  
  config: 
     import:  optional:configserver:http://localhost:8888
  
  
server:
 port: 3000
 
  