spring:
  application:
    name: AR_API
  

  config: 
     import:  optional:configserver:http://localhost:8888
  
server:
  port: 4042
ar:
 ssa-web:
    url: http://localhost:9090/ssa-web-api/find/{ssn}
 state: New Jersey


  