spring.application.name=CloudApiGateWay
server.port=4444


#Api gateway routes and predicate info
spring.cloud.gateway.routes[0].id=Admin_API
spring.cloud.gateway.routes[0].uri=http://localhost:4041/
spring.cloud.gateway.routes[0].predicates[0]=Path=/plan-api/**

spring.cloud.gateway.routes[1].id=AR_API
spring.cloud.gateway.routes[1].uri=http://localhost:4042/
spring.cloud.gateway.routes[1].predicates[0]=Path=/app/**

spring.cloud.gateway.routes[2].id=DC_API
spring.cloud.gateway.routes[2].uri=http://localhost:4043/
spring.cloud.gateway.routes[2].predicates[0]=Path=/dc-api/**

spring.cloud.gateway.routes[3].id=ED_API
spring.cloud.gateway.routes[3].uri=http://localhost:4044/
spring.cloud.gateway.routes[3].predicates[0]=Path=/Eligibility/**

spring.cloud.gateway.routes[4].id=CO_API
spring.cloud.gateway.routes[4].uri=http://localhost:3000/
spring.cloud.gateway.routes[4].predicates[0]=Path=/trigger/**

spring.cloud.gateway.routes[5].id=BI_API
spring.cloud.gateway.routes[5].uri=http://localhost:4046/
spring.cloud.gateway.routes[5].predicates[0]=Path=/bi-api/**

eureka.client.service-url.default-zone=http://localhot:8761/eureka